title: 我的AI转型之旅
email: your-email@example.com
description: >-
  一个工作13年的程序员的AI转型之路
baseurl: ""
url: "https://yourusername.github.io"
twitter_username: jekyllrb
github_username: jekyll

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
